/**
 * Minimal problem→pattern map for client-side pattern detection.
 * Generated from Swati's DSA Patterns Sheet (94 patterns, 15 categories).
 */

const PROBLEM_PATTERNS = {
  1:"Sliding Window > Character Frequency Matching",2:"Linked List > Number Addition",3:"Sliding Window > Variable Size",
  4:"Binary Search > Median/Kth",5:"Two Pointers > Expanding From Center",8:"String Manipulation > String to Integer",
  9:"String Manipulation > Palindrome Check",11:"Two Pointers > Converging",12:"String Manipulation > Roman Conversion",
  13:"String Manipulation > Roman Conversion",15:"Two Pointers > Converging",16:"Two Pointers > Converging",
  17:"Backtracking > Subsets",18:"Two Pointers > Converging",19:"Two Pointers > Fixed Separation",
  20:"Stack > Valid Parentheses",21:"Linked List > Merging Sorted Lists",22:"Backtracking > Parentheses Generation",
  23:"Linked List > Merging Sorted Lists",24:"Linked List > Reordering",25:"Linked List > In-place Reversal",
  26:"Two Pointers > In-place Array Modification",27:"Two Pointers > In-place Array Modification",
  28:"String Manipulation > String Matching",31:"Backtracking > Permutations",32:"Stack > Valid Parentheses",
  33:"Binary Search > Rotated Sorted Array",34:"Binary Search > First/Last Occurrence",
  35:"Binary Search > On Sorted Array",37:"Backtracking > N-Queens",39:"Backtracking > Combination Sum",
  40:"Backtracking > Combination Sum",41:"Array/Matrix > Cyclic Sort",43:"String Manipulation > Manual Simulation",
  45:"Greedy > Jump Game",46:"Backtracking > Permutations",48:"Array/Matrix > In-place Rotation",
  49:"String Manipulation > Anagram Check",51:"Backtracking > N-Queens",53:"Dynamic Programming > Kadane's Algorithm",
  54:"Array/Matrix > Spiral Traversal",55:"Greedy > Jump Game",56:"Greedy > Interval Merging",
  57:"Greedy > Interval Merging",59:"Array/Matrix > Spiral Traversal",60:"Backtracking > Permutations",
  61:"Linked List > Reordering",62:"Dynamic Programming > Unique Paths on Grid",
  63:"Dynamic Programming > Unique Paths on Grid",64:"Dynamic Programming > Unique Paths on Grid",
  65:"String Manipulation > String to Integer",66:"Array/Matrix > Plus One / Manual Arithmetic",
  67:"Array/Matrix > Plus One / Manual Arithmetic",69:"Binary Search > On Sorted Array",
  70:"Dynamic Programming > Fibonacci Style",71:"Stack > Simulation",72:"Dynamic Programming > Edit Distance",
  73:"Array/Matrix > In-place Marking",74:"Binary Search > On Sorted Array",
  75:"Two Pointers > In-place Array Modification",76:"Sliding Window > Variable Size",
  77:"Backtracking > Subsets",78:"Backtracking > Subsets",79:"Backtracking > Word Search",
  80:"Two Pointers > In-place Array Modification",81:"Binary Search > Rotated Sorted Array",
  82:"Linked List > In-place Reversal",83:"Linked List > In-place Reversal",
  84:"Stack > Largest Rectangle",85:"Stack > Largest Rectangle",86:"Linked List > Reordering",
  88:"Array/Matrix > In-place from End",90:"Backtracking > Subsets",91:"Dynamic Programming > Fibonacci Style",
  92:"Linked List > In-place Reversal",94:"Tree Traversal > Recursive Inorder",
  95:"Dynamic Programming > Catalan Numbers",96:"Dynamic Programming > Catalan Numbers",
  98:"Tree Traversal > Recursive Inorder",100:"Tree Traversal > Recursive Preorder",
  101:"Tree Traversal > Recursive Preorder",102:"Tree Traversal > Level Order Traversal",
  103:"Tree Traversal > Level Order Traversal",104:"Tree Traversal > Recursive Postorder",
  105:"Tree Traversal > Recursive Preorder",110:"Tree Traversal > Recursive Postorder",
  114:"Tree Traversal > Recursive Preorder",120:"Dynamic Programming > Unique Paths on Grid",
  121:"Dynamic Programming > Stock Problems",122:"Dynamic Programming > Stock Problems",
  123:"Dynamic Programming > Stock Problems",124:"Tree Traversal > Recursive Postorder",
  125:"String Manipulation > Palindrome Check",126:"Graph Traversal > Bidirectional BFS",
  127:"Graph Traversal > Bidirectional BFS",130:"Graph Traversal > DFS Connected Components",
  131:"Backtracking > Palindrome Partitioning",132:"Backtracking > Palindrome Partitioning",
  133:"Graph Traversal > Deep Copy/Cloning",134:"Greedy > Gas Station",135:"Greedy > Sorting Based",
  136:"Bit Manipulation > Bitwise XOR",137:"Bit Manipulation > Bitwise XOR",
  138:"Graph Traversal > Deep Copy/Cloning",139:"Dynamic Programming > Word Break Style",
  140:"Dynamic Programming > Word Break Style",141:"Two Pointers > Fast & Slow",
  143:"Linked List > Reordering",145:"Tree Traversal > Recursive Postorder",146:"Design > General Design",
  150:"Stack > Expression Evaluation",151:"Two Pointers > String Reversal",
  152:"Dynamic Programming > Kadane's Algorithm",153:"Binary Search > Rotated Sorted Array",
  155:"Stack > Min Stack Design",160:"Linked List > Intersection Detection",
  162:"Binary Search > Rotated Sorted Array",167:"Two Pointers > Converging",
  173:"Tree Traversal > Recursive Inorder",188:"Dynamic Programming > Stock Problems",
  189:"Array/Matrix > In-place Rotation",191:"Bit Manipulation > Bitwise AND",
  198:"Dynamic Programming > Fibonacci Style",199:"Tree Traversal > Level Order Traversal",
  200:"Graph Traversal > DFS Connected Components",202:"Two Pointers > Fast & Slow",
  206:"Linked List > In-place Reversal",207:"Graph Traversal > DFS Cycle Detection",
  208:"Design > Tries",209:"Sliding Window > Variable Size",210:"Graph Traversal > DFS Cycle Detection",
  211:"Design > Tries",212:"Backtracking > Word Search",213:"Dynamic Programming > Fibonacci Style",
  214:"String Manipulation > String Matching",215:"Heap (Priority Queue) > Top K Elements",
  219:"Sliding Window > Variable Size",221:"Dynamic Programming > Unique Paths on Grid",
  224:"Stack > Expression Evaluation",225:"Design > General Design",226:"Tree Traversal > Recursive Preorder",
  227:"Stack > Expression Evaluation",230:"Tree Traversal > Recursive Inorder",
  231:"Bit Manipulation > Bitwise AND",232:"Design > General Design",234:"Linked List > In-place Reversal",
  235:"Tree Traversal > Lowest Common Ancestor",236:"Tree Traversal > Lowest Common Ancestor",
  238:"Array/Matrix > Prefix/Suffix Products",239:"Sliding Window > Monotonic Queue",
  241:"Dynamic Programming > Catalan Numbers",242:"String Manipulation > Anagram Check",
  253:"Heap (Priority Queue) > Scheduling/Minimum Cost",257:"Tree Traversal > Recursive Preorder",
  259:"Two Pointers > Converging",268:"Bit Manipulation > Bitwise XOR",278:"Binary Search > On Sorted Array",
  283:"Two Pointers > In-place Array Modification",287:"Two Pointers > Fast & Slow",
  289:"Array/Matrix > In-place Marking",295:"Heap (Priority Queue) > Two Heaps",
  297:"Tree Traversal > Serialization/Deserialization",300:"Dynamic Programming > Longest Increasing Subsequence",
  301:"Backtracking > Parentheses Generation",309:"Dynamic Programming > Stock Problems",
  310:"Graph Traversal > BFS Topological Sort",312:"Dynamic Programming > Interval DP",
  322:"Dynamic Programming > Coin Change",328:"Linked List > Reordering",
  337:"Dynamic Programming > Fibonacci Style",338:"Bit Manipulation > Bitwise DP",
  342:"Bit Manipulation > Power Check",344:"Two Pointers > String Reversal",
  345:"Two Pointers > String Reversal",347:"Heap (Priority Queue) > Top K Elements",
  349:"Two Pointers > Converging",354:"Dynamic Programming > Longest Increasing Subsequence",
  373:"Heap (Priority Queue) > K-way Merge",374:"Binary Search > On Sorted Array",
  377:"Dynamic Programming > Coin Change",378:"Heap (Priority Queue) > K-way Merge",
  389:"Bit Manipulation > Bitwise XOR",392:"Two Pointers > Fast & Slow",394:"Stack > Simulation",
  402:"Stack > Monotonic Stack",406:"Greedy > Sorting Based",410:"Binary Search > On Answer (Binary Search on Result)",
  415:"String Manipulation > Manual Simulation",416:"Dynamic Programming > 0/1 Knapsack",
  417:"Graph Traversal > DFS Connected Components",424:"Sliding Window > Variable Size",
  438:"Sliding Window > Character Frequency Matching",442:"Array/Matrix > Cyclic Sort",
  443:"Two Pointers > In-place Array Modification",448:"Array/Matrix > Cyclic Sort",
  451:"Heap (Priority Queue) > Top K Elements",455:"Greedy > Sorting Based",
  459:"String Manipulation > Repeated Substring",477:"Bit Manipulation > Bitwise AND",
  494:"Dynamic Programming > 0/1 Knapsack",496:"Stack > Monotonic Stack",498:"Array/Matrix > In-place Marking",
  501:"Tree Traversal > Recursive Inorder",503:"Stack > Monotonic Stack",509:"Dynamic Programming > Fibonacci Style",
  518:"Dynamic Programming > Coin Change",530:"Tree Traversal > Recursive Inorder",
  540:"Binary Search > On Sorted Array",541:"Two Pointers > String Reversal",
  542:"Graph Traversal > BFS Connected Components",543:"Tree Traversal > Recursive Postorder",
  546:"Dynamic Programming > Interval DP",547:"Graph Traversal > DFS Connected Components",
  567:"Sliding Window > Character Frequency Matching",572:"Tree Traversal > Serialization/Deserialization",
  583:"Dynamic Programming > Edit Distance",599:"Linked List > Intersection Detection",
  621:"Greedy > Task Scheduling",632:"Heap (Priority Queue) > K-way Merge",
  643:"Sliding Window > Fixed Size",647:"Two Pointers > Expanding From Center",
  652:"Tree Traversal > Serialization/Deserialization",658:"Binary Search > First/Last Occurrence",
  680:"String Manipulation > Palindrome Check",684:"Graph Traversal > Union-Find",
  686:"String Manipulation > String Matching",695:"Graph Traversal > DFS Connected Components",
  703:"Heap (Priority Queue) > Top K Elements",704:"Binary Search > On Sorted Array",
  712:"Dynamic Programming > Edit Distance",713:"Sliding Window > Variable Size",
  719:"Binary Search > Median/Kth",721:"Graph Traversal > Union-Find",733:"Graph Traversal > DFS Connected Components",
  735:"Stack > Simulation",739:"Stack > Monotonic Stack",740:"Dynamic Programming > Fibonacci Style",
  743:"Graph Traversal > Shortest Path (Dijkstra)",746:"Dynamic Programming > Fibonacci Style",
  759:"Greedy > Interval Merging",767:"Greedy > Task Scheduling",772:"Stack > Expression Evaluation",
  774:"Binary Search > On Answer (Binary Search on Result)",778:"Graph Traversal > Shortest Path (Dijkstra)",
  787:"Graph Traversal > Shortest Path (Bellman-Ford)",796:"String Manipulation > String Matching",
  802:"Graph Traversal > DFS Cycle Detection",815:"Graph Traversal > Bidirectional BFS",
  841:"Graph Traversal > DFS Connected Components",844:"Two Pointers > String Comparison",
  845:"Array/Matrix > Prefix/Suffix Products",852:"Binary Search > Rotated Sorted Array",
  857:"Heap (Priority Queue) > Scheduling/Minimum Cost",862:"Sliding Window > Monotonic Queue",
  863:"Tree Traversal > Recursive Postorder",867:"Array/Matrix > In-place Rotation",
  875:"Binary Search > On Answer (Binary Search on Result)",876:"Two Pointers > Fixed Separation",
  881:"Two Pointers > Converging",885:"Array/Matrix > Spiral Traversal",
  895:"Stack > Min Stack Design",901:"Stack > Monotonic Stack",904:"Sliding Window > Variable Size",
  905:"Two Pointers > In-place Array Modification",907:"Stack > Monotonic Stack",
  918:"Dynamic Programming > Kadane's Algorithm",921:"Stack > Valid Parentheses",
  931:"Dynamic Programming > Unique Paths on Grid",947:"Graph Traversal > Union-Find",
  962:"Stack > Monotonic Stack",973:"Heap (Priority Queue) > Top K Elements",
  977:"Two Pointers > Converging",986:"Greedy > Interval Merging",
  988:"Tree Traversal > Recursive Preorder",989:"Array/Matrix > Plus One / Manual Arithmetic",
  994:"Graph Traversal > BFS Connected Components",1004:"Sliding Window > Variable Size",
  1011:"Binary Search > On Answer (Binary Search on Result)",1020:"Graph Traversal > DFS Connected Components",
  1029:"Greedy > Sorting Based",1046:"Heap (Priority Queue) > Top K Elements",
  1054:"Greedy > Task Scheduling",1091:"Graph Traversal > BFS Connected Components",
  1095:"Binary Search > Rotated Sorted Array",1110:"Tree Traversal > Recursive Postorder",
  1143:"Dynamic Programming > Longest Common Subsequence",1161:"Tree Traversal > Level Order Traversal",
  1192:"Graph Traversal > Strongly Connected Components",1249:"Stack > Valid Parentheses",
  1254:"Graph Traversal > DFS Connected Components",1277:"Dynamic Programming > Unique Paths on Grid",
  1438:"Sliding Window > Variable Size",1457:"Backtracking > Palindrome Partitioning",
  1475:"Stack > Monotonic Stack",1482:"Binary Search > On Answer (Binary Search on Result)",
  1493:"Sliding Window > Variable Size",1514:"Graph Traversal > Shortest Path (Dijkstra)",
  1539:"Binary Search > On Sorted Array",1584:"Graph Traversal > Minimum Spanning Tree",
  1631:"Graph Traversal > Shortest Path (Dijkstra)",1642:"Heap (Priority Queue) > Scheduling/Minimum Cost",
  1658:"Sliding Window > Variable Size",1671:"Dynamic Programming > Longest Increasing Subsequence",
  1673:"Stack > Monotonic Stack",1696:"Sliding Window > Monotonic Queue",
  1749:"Dynamic Programming > Kadane's Algorithm",1760:"Binary Search > On Answer (Binary Search on Result)",
  1825:"Heap (Priority Queue) > Two Heaps",1838:"Sliding Window > Variable Size",
  1905:"Graph Traversal > DFS Connected Components",1963:"Stack > Valid Parentheses",
  1976:"Graph Traversal > Shortest Path (Dijkstra)",2018:"Backtracking > Word Search",
  2045:"Graph Traversal > Shortest Path (Dijkstra)",2050:"Graph Traversal > BFS Topological Sort",
  2064:"Binary Search > On Answer (Binary Search on Result)",2095:"Two Pointers > Fixed Separation",
  2101:"Graph Traversal > DFS Connected Components",2202:"Greedy > Gas Station",
  2226:"Binary Search > On Answer (Binary Search on Result)",2290:"Graph Traversal > Shortest Path (Dijkstra)",
  2321:"Dynamic Programming > Kadane's Algorithm",2337:"Two Pointers > In-place Array Modification",
  2390:"Two Pointers > String Comparison",2392:"Graph Traversal > BFS Topological Sort",
  2406:"Greedy > Interval Merging",2407:"Dynamic Programming > Longest Increasing Subsequence",
  2458:"Tree Traversal > Recursive Postorder",2461:"Sliding Window > Variable Size",
  2516:"Sliding Window > Variable Size",2558:"Heap (Priority Queue) > Top K Elements",
  2577:"Graph Traversal > Shortest Path (Dijkstra)",2762:"Sliding Window > Variable Size",
  2779:"Sliding Window > Variable Size",2812:"Graph Traversal > Shortest Path (Dijkstra)",
  2938:"Two Pointers > In-place Array Modification",2981:"Sliding Window > Variable Size",
  3008:"String Manipulation > String Matching",3026:"Sliding Window > Variable Size",
  3346:"Sliding Window > Variable Size",3347:"Sliding Window > Variable Size"
};

// All pattern labels for the dropdown
const PATTERN_LABELS = [
  "Two Pointers > Converging","Two Pointers > Fast & Slow","Two Pointers > Fixed Separation",
  "Two Pointers > In-place Array Modification","Two Pointers > String Comparison",
  "Two Pointers > Expanding From Center","Two Pointers > String Reversal",
  "Sliding Window > Fixed Size","Sliding Window > Variable Size","Sliding Window > Monotonic Queue",
  "Sliding Window > Character Frequency Matching",
  "Tree Traversal > Level Order Traversal","Tree Traversal > Recursive Preorder",
  "Tree Traversal > Recursive Inorder","Tree Traversal > Recursive Postorder",
  "Tree Traversal > Lowest Common Ancestor","Tree Traversal > Serialization/Deserialization",
  "Graph Traversal > DFS Connected Components","Graph Traversal > BFS Connected Components",
  "Graph Traversal > DFS Cycle Detection","Graph Traversal > BFS Topological Sort",
  "Graph Traversal > Deep Copy/Cloning","Graph Traversal > Shortest Path (Dijkstra)",
  "Graph Traversal > Shortest Path (Bellman-Ford)","Graph Traversal > Union-Find",
  "Graph Traversal > Strongly Connected Components","Graph Traversal > Bridges & Articulation Points",
  "Graph Traversal > Minimum Spanning Tree","Graph Traversal > Bidirectional BFS",
  "Dynamic Programming > Fibonacci Style","Dynamic Programming > Kadane's Algorithm",
  "Dynamic Programming > Coin Change","Dynamic Programming > 0/1 Knapsack",
  "Dynamic Programming > Word Break Style","Dynamic Programming > Longest Common Subsequence",
  "Dynamic Programming > Edit Distance","Dynamic Programming > Unique Paths on Grid",
  "Dynamic Programming > Interval DP","Dynamic Programming > Catalan Numbers",
  "Dynamic Programming > Longest Increasing Subsequence","Dynamic Programming > Stock Problems",
  "Heap (Priority Queue) > Top K Elements","Heap (Priority Queue) > Two Heaps",
  "Heap (Priority Queue) > K-way Merge","Heap (Priority Queue) > Scheduling/Minimum Cost",
  "Backtracking > Subsets","Backtracking > Permutations","Backtracking > Combination Sum",
  "Backtracking > Parentheses Generation","Backtracking > Word Search","Backtracking > N-Queens",
  "Backtracking > Palindrome Partitioning",
  "Greedy > Interval Merging","Greedy > Jump Game","Greedy > Buy/Sell Stock",
  "Greedy > Gas Station","Greedy > Task Scheduling","Greedy > Sorting Based",
  "Binary Search > On Sorted Array","Binary Search > Rotated Sorted Array",
  "Binary Search > On Answer (Binary Search on Result)","Binary Search > First/Last Occurrence",
  "Binary Search > Median/Kth",
  "Stack > Valid Parentheses","Stack > Monotonic Stack","Stack > Expression Evaluation",
  "Stack > Simulation","Stack > Min Stack Design","Stack > Largest Rectangle",
  "Bit Manipulation > Bitwise XOR","Bit Manipulation > Bitwise AND",
  "Bit Manipulation > Bitwise DP","Bit Manipulation > Power Check",
  "Linked List > In-place Reversal","Linked List > Merging Sorted Lists",
  "Linked List > Number Addition","Linked List > Intersection Detection","Linked List > Reordering",
  "Array/Matrix > In-place Rotation","Array/Matrix > Spiral Traversal",
  "Array/Matrix > In-place Marking","Array/Matrix > Prefix/Suffix Products",
  "Array/Matrix > Plus One / Manual Arithmetic","Array/Matrix > In-place from End",
  "Array/Matrix > Cyclic Sort",
  "String Manipulation > Palindrome Check","String Manipulation > Anagram Check",
  "String Manipulation > Roman Conversion","String Manipulation > String to Integer",
  "String Manipulation > Manual Simulation","String Manipulation > String Matching",
  "String Manipulation > Repeated Substring",
  "Design > General Design","Design > Tries"
];

/**
 * Extract LeetCode problem slug from a URL.
 * @param {string} url
 * @returns {string|null}
 */
function extractLeetCodeSlug(url) {
  const m = url.match(/leetcode\.com\/problems\/([^/]+)/);
  return m ? m[1].toLowerCase() : null;
}

// Slug → problem number reverse map (built from PROBLEM_PATTERNS keys + known slugs)
// We only need to detect by URL, so we embed slug→number for known problems
const SLUG_TO_NUMBER = {
  "two-sum":1,"add-two-numbers":2,"longest-substring-without-repeating-characters":3,
  "median-of-two-sorted-arrays":4,"longest-palindromic-substring":5,"string-to-integer-atoi":8,
  "palindrome-number":9,"container-with-most-water":11,"integer-to-roman":12,
  "roman-to-integer":13,"3sum":15,"3sum-closest":16,
  "letter-combinations-of-a-phone-number":17,"4sum":18,"remove-nth-node-from-end-of-list":19,
  "valid-parentheses":20,"merge-two-sorted-lists":21,"generate-parentheses":22,
  "merge-k-sorted-lists":23,"swap-nodes-in-pairs":24,"reverse-nodes-in-k-group":25,
  "remove-duplicates-from-sorted-array":26,"remove-element":27,
  "find-the-index-of-the-first-occurrence-in-a-string":28,"next-permutation":31,
  "longest-valid-parentheses":32,"search-in-rotated-sorted-array":33,
  "find-first-and-last-position-of-element-in-sorted-array":34,
  "search-insert-position":35,"sudoku-solver":37,"combination-sum":39,
  "combination-sum-ii":40,"first-missing-positive":41,"multiply-strings":43,
  "jump-game-ii":45,"permutations":46,"rotate-image":48,
  "group-anagrams":49,"n-queens":51,"maximum-subarray":53,
  "spiral-matrix":54,"jump-game":55,"merge-intervals":56,
  "insert-interval":57,"spiral-matrix-ii":59,"permutation-sequence":60,
  "rotate-list":61,"unique-paths":62,"unique-paths-ii":63,
  "minimum-path-sum":64,"valid-number":65,"plus-one":66,
  "add-binary":67,"sqrtx":69,"climbing-stairs":70,
  "simplify-path":71,"edit-distance":72,"set-matrix-zeroes":73,
  "search-a-2d-matrix":74,"sort-colors":75,"minimum-window-substring":76,
  "combinations":77,"subsets":78,"word-search":79,
  "remove-duplicates-from-sorted-array-ii":80,"search-in-rotated-sorted-array-ii":81,
  "remove-duplicates-from-sorted-list-ii":82,"remove-duplicates-from-sorted-list":83,
  "largest-rectangle-in-histogram":84,"maximal-rectangle":85,
  "partition-list":86,"merge-sorted-array":88,"subsets-ii":90,
  "decode-ways":91,"reverse-linked-list-ii":92,"binary-tree-inorder-traversal":94,
  "unique-binary-search-trees-ii":95,"unique-binary-search-trees":96,
  "validate-binary-search-tree":98,"same-tree":100,"symmetric-tree":101,
  "binary-tree-level-order-traversal":102,"binary-tree-zigzag-level-order-traversal":103,
  "maximum-depth-of-binary-tree":104,
  "construct-binary-tree-from-preorder-and-inorder-traversal":105,
  "balanced-binary-tree":110,"flatten-binary-tree-to-linked-list":114,
  "triangle":120,"best-time-to-buy-and-sell-stock":121,
  "best-time-to-buy-and-sell-stock-ii":122,"best-time-to-buy-and-sell-stock-iii":123,
  "binary-tree-maximum-path-sum":124,"valid-palindrome":125,
  "word-ladder-ii":126,"word-ladder":127,"surrounded-regions":130,
  "palindrome-partitioning":131,"palindrome-partitioning-ii":132,
  "clone-graph":133,"gas-station":134,"candy":135,
  "single-number":136,"single-number-ii":137,"copy-list-with-random-pointer":138,
  "word-break":139,"word-break-ii":140,"linked-list-cycle":141,
  "reorder-list":143,"binary-tree-postorder-traversal":145,
  "lru-cache":146,"evaluate-reverse-polish-notation":150,
  "reverse-words-in-a-string":151,"maximum-product-subarray":152,
  "find-minimum-in-rotated-sorted-array":153,"min-stack":155,
  "intersection-of-two-linked-lists":160,"find-peak-element":162,
  "two-sum-ii-input-array-is-sorted":167,"binary-search-tree-iterator":173,
  "best-time-to-buy-and-sell-stock-iv":188,"rotate-array":189,
  "number-of-1-bits":191,"house-robber":198,"binary-tree-right-side-view":199,
  "number-of-islands":200,"happy-number":202,"reverse-linked-list":206,
  "course-schedule":207,"implement-trie-prefix-tree":208,
  "minimum-size-subarray-sum":209,"course-schedule-ii":210,
  "design-add-and-search-words-data-structure":211,"word-search-ii":212,
  "house-robber-ii":213,"shortest-palindrome":214,
  "kth-largest-element-in-an-array":215,"contains-duplicate-ii":219,
  "maximal-square":221,"basic-calculator":224,"implement-stack-using-queues":225,
  "invert-binary-tree":226,"basic-calculator-ii":227,
  "kth-smallest-element-in-a-bst":230,"power-of-two":231,
  "implement-queue-using-stacks":232,"palindrome-linked-list":234,
  "lowest-common-ancestor-of-a-binary-search-tree":235,
  "lowest-common-ancestor-of-a-binary-tree":236,
  "product-of-array-except-self":238,"sliding-window-maximum":239,
  "different-ways-to-add-parentheses":241,"valid-anagram":242,
  "meeting-rooms-ii":253,"binary-tree-paths":257,"3sum-smaller":259,
  "missing-number":268,"first-bad-version":278,"move-zeroes":283,
  "find-the-duplicate-number":287,"game-of-life":289,
  "find-median-from-data-stream":295,"serialize-and-deserialize-binary-tree":297,
  "longest-increasing-subsequence":300,"remove-invalid-parentheses":301,
  "best-time-to-buy-and-sell-stock-with-cooldown":309,"minimum-height-trees":310,
  "burst-balloons":312,"coin-change":322,"odd-even-linked-list":328,
  "house-robber-iii":337,"counting-bits":338,"reverse-string":344,
  "reverse-vowels-of-a-string":345,"top-k-frequent-elements":347,
  "intersection-of-two-arrays":349,"russian-doll-envelopes":354,
  "find-k-pairs-with-smallest-sums":373,"guess-number-higher-or-lower":374,
  "combination-sum-iv":377,"kth-smallest-element-in-a-sorted-matrix":378,
  "find-the-difference":389,"is-subsequence":392,"decode-string":394,
  "remove-k-digits":402,"queue-reconstruction-by-height":406,
  "split-array-largest-sum":410,"add-strings":415,
  "partition-equal-subset-sum":416,"pacific-atlantic-water-flow":417,
  "longest-repeating-character-replacement":424,
  "find-all-anagrams-in-a-string":438,"find-all-duplicates-in-an-array":442,
  "string-compression":443,"find-all-numbers-disappeared-in-an-array":448,
  "sort-characters-by-frequency":451,"assign-cookies":455,
  "repeated-substring-pattern":459,"total-hamming-distance":477,
  "target-sum":494,"next-greater-element-i":496,"diagonal-traverse":498,
  "find-mode-in-binary-search-tree":501,"next-greater-element-ii":503,
  "fibonacci-number":509,"coin-change-ii":518,
  "minimum-absolute-difference-in-bst":530,"single-element-in-a-sorted-array":540,
  "reverse-string-ii":541,"01-matrix":542,"diameter-of-binary-tree":543,
  "remove-boxes":546,"number-of-provinces":547,"permutation-in-string":567,
  "subtree-of-another-tree":572,"delete-operation-for-two-strings":583,
  "task-scheduler":621,"maximum-average-subarray-i":643,
  "palindromic-substrings":647,"find-duplicate-subtrees":652,
  "find-k-closest-elements":658,"valid-palindrome-ii":680,
  "redundant-connection":684,"repeated-string-match":686,
  "max-area-of-island":695,"kth-largest-element-in-a-stream":703,
  "binary-search":704,"minimum-ascii-delete-sum-for-two-strings":712,
  "subarray-product-less-than-k":713,"find-k-th-smallest-pair-distance":719,
  "accounts-merge":721,"flood-fill":733,"asteroid-collision":735,
  "daily-temperatures":739,"delete-and-earn":740,"network-delay-time":743,
  "min-cost-climbing-stairs":746,"employee-free-time":759,
  "reorganize-string":767,"basic-calculator-iii":772,
  "swim-in-rising-water":778,"cheapest-flights-within-k-stops":787,
  "rotate-string":796,"find-eventual-safe-states":802,"bus-routes":815,
  "keys-and-rooms":841,"backspace-string-compare":844,
  "longest-mountain-in-array":845,"peak-index-in-a-mountain-array":852,
  "minimum-cost-to-hire-k-workers":857,"shortest-subarray-with-sum-at-least-k":862,
  "all-nodes-distance-k-in-binary-tree":863,"transpose-matrix":867,
  "koko-eating-bananas":875,"middle-of-the-linked-list":876,
  "boats-to-save-people":881,"spiral-matrix-iii":885,
  "maximum-frequency-stack":895,"online-stock-span":901,
  "fruit-into-baskets":904,"sort-array-by-parity":905,
  "sum-of-subarray-minimums":907,"maximum-sum-circular-subarray":918,
  "minimum-add-to-make-parentheses-valid":921,"minimum-falling-path-sum":931,
  "most-stones-removed-with-same-row-or-column":947,"maximum-width-ramp":962,
  "k-closest-points-to-origin":973,"squares-of-a-sorted-array":977,
  "interval-list-intersections":986,"smallest-string-starting-from-leaf":988,
  "add-to-array-form-of-integer":989,"rotting-oranges":994,
  "max-consecutive-ones-iii":1004,"capacity-to-ship-packages-within-d-days":1011,
  "number-of-enclaves":1020,"two-city-scheduling":1029,
  "last-stone-weight":1046,"distant-barcodes":1054,
  "shortest-path-in-binary-matrix":1091,
  "find-in-mountain-array":1095,"delete-nodes-and-return-forest":1110,
  "longest-common-subsequence":1143,
  "maximum-level-sum-of-a-binary-tree":1161,
  "critical-connections-in-a-network":1192,
  "minimum-remove-to-make-valid-parentheses":1249,
  "number-of-closed-islands":1254,
  "count-square-submatrices-with-all-ones":1277,
  "longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit":1438,
  "pseudo-palindromic-paths-in-a-binary-tree":1457,
  "final-prices-with-a-special-discount-in-a-shop":1475,
  "minimum-number-of-days-to-make-m-bouquets":1482,
  "longest-subarray-of-1s-after-deleting-one-element":1493,
  "path-with-maximum-probability":1514,"kth-missing-positive-number":1539,
  "min-cost-to-connect-all-points":1584,
  "path-with-minimum-effort":1631,"furthest-building-you-can-reach":1642,
  "minimum-operations-to-reduce-x-to-zero":1658,
  "minimum-number-of-removals-to-make-mountain-array":1671,
  "find-the-most-competitive-subsequence":1673,
  "jump-game-vi":1696,"maximum-absolute-sum-of-any-subarray":1749,
  "minimum-limit-of-balls-in-a-bag":1760,
  "finding-mk-average":1825,
  "frequency-of-the-most-frequent-element":1838,
  "count-sub-islands":1905,"minimum-number-of-swaps-to-make-the-string-balanced":1963,
  "number-of-ways-to-arrive-at-destination":1976,
  "check-if-word-can-be-placed-in-crossword":2018,
  "second-minimum-time-to-reach-destination":2045,
  "parallel-courses-iii":2050,
  "minimized-maximum-of-products-distributed-to-any-store":2064,
  "delete-the-middle-node-of-a-linked-list":2095,
  "detonate-the-maximum-bombs":2101,
  "maximize-the-topmost-element-after-k-moves":2202,
  "maximum-candies-allocated-to-k-children":2226,
  "minimum-obstacle-removal-to-reach-corner":2290,
  "maximum-score-of-a-good-subarray":2321,
  "move-pieces-to-obtain-a-string":2337,
  "removing-stars-from-a-string":2390,
  "build-a-matrix-with-conditions":2392,
  "divide-intervals-into-minimum-number-of-groups":2406,
  "longest-increasing-subsequence-ii":2407,
  "height-of-binary-tree-after-subtree-removal-queries":2458,
  "maximum-sum-of-distinct-subarrays-with-length-k":2461,
  "take-k-of-each-character-from-left-and-right":2516,
  "take-gifts-from-the-richest-pile":2558,
  "minimum-time-to-visit-a-cell-in-a-grid":2577,
  "continuous-subarrays":2762,
  "maximum-beauty-of-an-array-after-applying-operation":2779,
  "find-the-safest-path-in-a-grid":2812,
  "separate-black-and-white-balls":2938,
  "find-longest-special-substring-that-occurs-thrice-i":2981,
  "maximum-good-subarray-sum":3026,
  "find-the-power-of-k-size-subarrays-i":3254,
  "find-x-sum-of-all-k-long-subarrays-i":3318,
  "maximum-frequency-of-an-element-after-performing-operations-i":3346,
  "maximum-frequency-of-an-element-after-performing-operations-ii":3347
};

/**
 * Detect pattern for a URL. Returns pattern label string or null.
 * @param {string} url
 * @returns {string|null}
 */
function detectPattern(url) {
  const slug = extractLeetCodeSlug(url);
  if (!slug) return null;
  const num = SLUG_TO_NUMBER[slug];
  if (!num) return null;
  return PROBLEM_PATTERNS[num] || null;
}
